package edu.orangecoastcollege.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;

public class ChooseScene {
	@FXML
	private Button foodButton;
	@FXML
	private Button TransportationButton;
	@FXML
	private Button RealEstate;
	@FXML
	private Button Back;

	// Event Listener on Button[#foodButton].onAction
	@FXML
	public void FoodButtonTrans(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#foodButton].onMouseClicked
	@FXML
	public void foodTransitionButton(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#TransportationButton].onAction
	@FXML
	public void TransportationButtonTrans(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#TransportationButton].onMouseClicked
	@FXML
	public void TransportationButton(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#RealEstate].onAction
	@FXML
	public void housingButtonTrans(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#RealEstate].onMouseClicked
	@FXML
	public void RealEstateButton(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Back].onAction
	@FXML
	public void backToCountryButton(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Back].onMouseClicked
	@FXML
	public void BacktoChoosesCountry(MouseEvent event) {
		// TODO Autogenerated
	}
}
