package edu.orangecoastcollege.view;

import edu.orangecoastcollege.controller.Controller;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;

public class CountryCityScene {

	// Event Listener on Button.onAction
	@FXML
	public void backButton(ActionEvent event) {
		// TODO Autogenerated
	       ViewNavigator.loadScene("User Info", ViewNavigator.USER_INFORMATION_SCENE);
	       Controller.countryChoosen=0;
	}

    @FXML
    public void goToChooseScene(ActionEvent event)
    {
        Object object = event.getSource();
        if (object instanceof Button)
        {
            Button b = (Button) object;
            String name = b.getId();
           if(name!=null){
            switch(name)
            {
                case "USA":
                    Controller.countryChoosen=1;
                    break;
                case"UK":
                    Controller.countryChoosen=2;
               break;
                case"SPAIN":
                    Controller.countryChoosen=3;
                    break;
                case "JAPAN":
                    Controller.countryChoosen=4;
                    break;
                case "BRAZIL":
                    Controller.countryChoosen=5;
                    break;
                case "VIETNAM":
                    Controller.countryChoosen=6;
                    break;
               
            }
           }
           System.out.println(Controller.countryChoosen);
        }
        ViewNavigator.loadScene("User Info", ViewNavigator.CHOOSE_SCENE);
     //Event e = new Event();

    }

}
