package edu.orangecoastcollege.view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.controller.Controller;
import edu.orangecoastcollege.model.Country;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.ListView;

public class Emailu implements Initializable{
	@FXML
	private Label emailErrorLabel;
	@FXML
	private Label getUserName;
	@FXML
	private Label getEmail;
	@FXML
	ListView<Country> countriesLV;
	
	private Controller controller = Controller.getInstance();
	// Event Listener on Button.onAction
	@FXML
	public void sendEmailFromView(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void goBackButton(ActionEvent event) {
	      
		ViewNavigator.loadScene("choose category", ViewNavigator.CHOOSE_SCENE);
	}
	
	@FXML
	public void showStats(ActionEvent event) {
	      
		ViewNavigator.loadScene("Stats", ViewNavigator.STATS);
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		countriesLV.setItems(controller.getAllCountriesList());
	}
}
