package edu.orangecoastcollege.view;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import edu.orangecoastcollege.controller.Controller;
import edu.orangecoastcollege.model.Country;
import edu.orangecoastcollege.model.Grocery;
import edu.orangecoastcollege.model.convertions;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.ListView;

public class FoodScene implements Initializable, convertions {

private static Controller controller = Controller.getInstance();
	
	@FXML
	private ListView<Grocery>foodLV;
	// Event Listener on Button.onAction
	@FXML
	public void BackToChooseScene(ActionEvent event) {
		// TODO Autogenerated
        ViewNavigator.loadScene("Categories", ViewNavigator.CHOOSE_SCENE);

	}

	public void addToSaveList(ActionEvent event) {
		
		for (Grocery f : controller.getAllGroceries()) 
		{	if(f.getCountry_code() == Integer.valueOf(Controller.countryChoosen))
			controller.saveList.add(f);

		}

		Controller.generateMessage();
	}
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		ObservableList<Grocery> counrty = FXCollections.observableArrayList();
	for(Grocery g:controller.getAllGroceries())
	{
		if(g.getCountry_code() == Integer.valueOf(Controller.countryChoosen))
			counrty.add(g);
	}
		foodLV.setItems(counrty);
	}

	@Override
	public boolean addFinalScene() {
		Grocery selected = foodLV.getSelectionModel().getSelectedItem();
	    // 2) Use the controller to add the selected game to the inventory
	return controller.addToFinalList(selected);
	
	}
}
