package edu.orangecoastcollege.view;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class HouseScene {

	// Event Listener on Button.onAction
	@FXML
	public void BackToChooseScene(ActionEvent event) {
		// TODO Autogenerated
        ViewNavigator.loadScene("categories", ViewNavigator.CHOOSE_SCENE);

	}
}
