package edu.orangecoastcollege.view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.chart.PieChart;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ToggleButton;

public class Statistics implements Initializable{
	@FXML
	private Button BackButton;
	@FXML
	private ToggleButton exitButton;

	@FXML
	PieChart pieChart;
	// Event Listener on Button[#BackButton].onAction
	@FXML
	public void BackToEmail(ActionEvent event) {
		// TODO Autogenerated
        ViewNavigator.loadScene("Result", ViewNavigator.Email);

	}
	// Event Listener on ToggleButton[#exitButton].onAction
	@FXML
	public void ClossApp(ActionEvent event) {
		// TODO Autogenerated
		System.exit(0);
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		   ObservableList<PieChart.Data> pieChartData =
	                FXCollections.observableArrayList(
	                new PieChart.Data("Spain", 13),
	                new PieChart.Data("USA", 25),
	                new PieChart.Data("Vietnem", 10),
	                new PieChart.Data("Japan", 22),
	                new PieChart.Data("UK", 30));
		   pieChart.setData(pieChartData);
		   pieChart.setTitle("Travel Expenses");
	}
	  
}
