package edu.orangecoastcollege.view;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.ListView;

import java.net.URL;
import java.util.ResourceBundle;

import edu.orangecoastcollege.controller.Controller;
import edu.orangecoastcollege.model.Grocery;
import edu.orangecoastcollege.model.Transportation;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

public class TransportationScene implements Initializable 
{

private static Controller controller = Controller.getInstance();
	
	@FXML
	private ListView<Transportation>transLV;
	
	@FXML
	public void BackToChooseScene(ActionEvent event) {
		// TODO Autogenerated
        ViewNavigator.loadScene("Categories", ViewNavigator.CHOOSE_SCENE);

	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		ObservableList<Transportation> counrty = FXCollections.observableArrayList();
		for(Transportation t:controller.getAllTransportation())
		{
			if(t.getCountry_code() == Integer.valueOf(Controller.countryChoosen))
				counrty.add(t);
		}
		transLV.setItems(counrty);
	}
}
